# Generated by Django 2.2.2 on 2019-07-02 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190702_1723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyrecord',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='habit',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='dailyrecord',
            unique_together={('entry', 'date')},
        ),
    ]
